### ISSUE TITLE
Generated definition and implementation resources files are unclear

### ISSUE THREAD

**Issue by laurentleseigneur** [bonitasoft/bonita-connector-archetype#33]
**Is your feature request related to a problem? Please describe.**
when using this archetype, generated files don't follow same pattern as in studio

**Describe the solution you'd like**
since those two files are `.xml` files, i'd like to just have `definition.xml` and `implementation.xml`resoursource file, so i can benefit from xml IDE completion feature based on provided XSD
then build step should apply replacements and rename as expected in studio aka `<definitionId>-<definitionVersion>.def` and `<implementationId>-<implementationVersion>.impl`. definition Id and implementation Id may be just the archetype id (in the maven way 

**Describe alternatives you've considered**
i did a manual update of generated files in order to make the connector work as expected in the studio (7.10.1 EE version)

**Additional context**
seem BCD can't deploy and enable process as expected (in same version)

**Comment by alachambre** [comment]
Hi, 

I'll consider the idea of generate XML files and rename them at build time, thanks for the idea. 
Concerning Definition and Implementation ID, it cannot be the same field, a definition can be implemented several times. 
I don't understand the BCD part of the issue? 

Thanks for the feedback!
Adrien

**Comment by uguy** [comment]
Hi Laurent, 
Could we have more details on the BCD part ?
Thanks

**Comment by laurentleseigneur** [comment]
BCD part of the issue is https://bonitasoft.atlassian.net/browse/BCD-397 that is still in review

**Comment by uguy** [comment]
Ok thanks !

**Comment by uguy** [comment]
As a quick fix for syntax support in intellij, you  can go to settings > file types and register new patterns for XML syntax (according your connector name has `connector` in its name):
- `*connector*.def`
- `*connector*.impl`

This won't break other association (like kotlin/cnative for `.def` file) and show bonita files as XML files in editor.

**Comment by uguy** [comment]
Hi, I'm closing this issue as explained in PR #34 .
